### ISSUE TITLE
RSI missing

### ISSUE THREAD

**Issue by think-nice-things** [jealous/stockstats#1]
very useful package, thanks!

What I'm missing is RSI (see https://en.wikipedia.org/wiki/Relative_strength_index)
and a bit more verbose documentation ;-)

Would it be hard to implement RSI?

**Comment by jealous** [comment]
Mm...  Yes, I remember that I have tried to implement it before and the algorithm is quite different from the others.  It's hard to utilize the tools supplied by pandas.  I will do some investigation and let you know if I have the effort to implement it.

**Comment by jealous** [comment]
RSI is implemented in the latest version.
Please use `stock['rsi_6']` to access 6 days RSI.  And `6` can be changed to other window sizes.

**Comment by think-nice-things** [comment]
thanks!
