### ISSUE TITLE
Get all indicators

### ISSUE THREAD

**Issue by camrongodbout** [jealous/stockstats#11]
I think this would be an interesting feature that I'd be willing to help out with. 

Ideally you could call a function similar to `df.get_stock_stats()` that returns a data frame with every single indicator.

any advice?

**Comment by jealous** [comment]
Hm, good idea.  I think you could just compose a list of indicators and initialize them in the `get_stock_stats` function.  What's more, I guess some intermediate stats may be generated, you could delete them in the function to save others' effort as well.  Just file a PR when you are done.  Any help is welcome 😄

**Comment by derdigge** [comment]
+1

This is ecxatly what i need, i have trouble to figure all indicators "calls" out.
Great project BTW

**Comment by mw0401** [comment]
I could use this also. I can't seem to get a valid list of indicators or what fields that they will generate.
I tried using mstd and mvar and just got errors.

**Comment by jealous** [comment]
Use `init_all()` to initialize all statistics with shortcuts.  Available from 0.4.1
