### ISSUE TITLE
Trying to find a list of all supported indicators

### ISSUE THREAD

**Issue by 39xdgy** [jealous/stockstats#117]
Hi 

I am working on a project for auto trading and I wonder if you have a function for me to grab all the indicators that you are supporting right now? thx

**Comment by roshanjain77** [comment]
You can refer to documentation to know all the indicators. [docs](https://pypi.org/project/stockstats/)

You can also use df.init_all(), where df is the dataframe. But I wouldn't recommend it. It generates many tables and can be slow for large data. This generates many columns showing different indicators.
