### ISSUE TITLE
Is comparison operator still supported?

### ISSUE THREAD

**Issue by isiosia** [jealous/stockstats#132]
I'm glad to see this fantastic work resume updating. Excellent work, and many thanks.

It seems that all the comparison operators have been removed since commit `68f105de6019525b8e940ae369eed308d1065ec5`, although I think they are quite an important feature in my case (ee.g. `kdjj_0_le_15_c`).

Is there any way to do the same thing in the new version? Or do I have to do this comparison by myself?

Anyway, there are still "compare: le, ge, lt, gt, eq, ne" in the new readme file, so I think there might be something going on...

**Comment by jealous** [comment]
No, they are not supported any more.  Just use the operators such as `>`, `<` between the columns to compare them.  Pandas has already done the job.
