### ISSUE TITLE
be able to use "retype" with multi-index dataframe indexed with 'ticker' and 'date'

### ISSUE THREAD

**Issue by M00NSH0T** [jealous/stockstats#14]
this is more a feature request.  

Basically, it's really easy to pull these bulk download sheets of daily stock data from sources like quandl that have the ticker as a column, then the date for each line of data.  If I want to use stockstats properly to calculate DMI or whatever, it looks like I need to use a for loop to iterate through each stock one by one.  It'd be much cooler if I could simply use 'retype()' on a dataframe indexed with both ticker and date.  I am actually able to do this now (surprisingly), and it runs very quickly even over 15k tickers spanning several years, but the problem is the 14 period moving averages and things like that seem to use the previous stock's data.  Since I'm looking at several years of data, this is only an issue for stocks that IPO'd recently, but it would still be nice if the code had some 'if' statements or whatever to check whether a line should be included in the moving average calculations when used this way.  It'd be a cool way to make this even easier to use, in my opinion.

**Comment by jealous** [comment]
Good point.  Let me think of it.

**Comment by jealous** [comment]
I plan to exclude this from the project's requirement.  Users need to prepare the data by their own.
