### ISSUE TITLE
Add support for different STD and SMA settings in Bollinger Bands

### ISSUE THREAD

**Issue by ericbhanson** [jealous/stockstats#15]
Being able to set the standard deviation and SMA amounts when calculating Bollinger Bands would be helpful to eliminate noise using a Mean Revision strategy (see https://marketfy.com/content/74202-how-to-trade-mean-reversion-setups for an example). Would be happy to work on this.

**Comment by jealous** [comment]
Hi @ericbhanson ,
As I mentioned in the comment of the PR, please use following code to change them:
``` python
StockDataFrame.BOLL_PERIOD = 10   # or other values you need
StockDataFrame.BOLL_STD_TIMES = 2.5
```
