### ISSUE TITLE
Cross lines indicator error

### ISSUE THREAD

**Issue by egrafeuille** [jealous/stockstats#18]
Hi,
What a wonderful tool you have created!
I'm facing the following error using cross line indicator:

`_ = chart['close_x_close_30_ema']`

C:\Users\grafeer\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\function_base.py in diff(a, n, axis)
```
   1924         return diff(a[slice1]-a[slice2], n-1, axis=axis)
   1925     else:
-> 1926         return a[slice1]-a[slice2]
   1927 
   1928 

```
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

I'm using numpy 1.13.0 version

**Comment by jealous** [comment]
Hi @egrafeuille , sorry for the late reply.
I can't reproduce it with my data set.  Could you share your data set?

**Comment by jealous** [comment]
Close due to no response.
