### ISSUE TITLE
UserWarning: Invalid number of return arguments after parsing column name: 'Date'

### ISSUE THREAD

**Issue by laurentvv** [jealous/stockstats#181]
`import yfinance as yf
from stockstats import StockDataFrame

ticker = "O"
start = "2022-01-01"
end = "2023-11-02"

df = yf.download(ticker, start, end)
stock_df = StockDataFrame.retype(df)

stock_df = stock_df[
    [
        "open",
        "high",
        "low",
        "close",
        "adj close",
        "volume",
        "rsi",
        "macd",
        "stochrsi",
        "vwma",
        "close_200_ema",
        "close_100_ema",
        "close_30_ema",
        "close_10_ema",
        "vr",
        "wr",
        "supertrend",
        "dma",
        "pdi",
        "ndi",
        "chop",
        "mfi",
    ]
]

stock_df = stock_df.dropna(axis=0)
stock_df["mean_year_close"] = stock_df.groupby(stock_df.index.year)["close"].transform("mean")

print(stock_df.tail())`

Works with pandas-2.1.1

Not working with  pandas 2.1.2 :
stock_df["mean_year_close"] = stock_df.groupby(stock_df.index.year)["close"].transform("mean")
UserWarning: Invalid number of return arguments after parsing column name: 'Date'

**Comment by laurentvv** [comment]
It's working with pandas-2.1.3....

**Comment by jealous** [comment]
Seems like a pandas regression in 2.1.2.  I am closing this for now.
