### ISSUE TITLE
Cannot wrap yfinance since 0.2.45+

### ISSUE THREAD

**Issue by satoshi** [jealous/stockstats#187]
Hi,

It's difficult to say who needs to fix what here, but I'm reporting that stockstats does not seem to be able to wrap yfinance 0.2.45 or newer.

Here's my sample code to illustrate the issue (using stockstats 0.6.2 and yfinance 0.2.51)
```
import yfinance as yf
from stockstats import wrap

data = yf.download('VIXY')
df = wrap(data)
print(df)

<snip>

  File "/home/satoshi/foo/venv/lib/python3.12/site-packages/stockstats.py", line 1961, in <lambda>
    value.columns = map(lambda c: c.lower(), value.columns)
                                  ^^^^^^^
AttributeError: 'tuple' object has no attribute 'lower'
```
I know stockstats isn't meant specifically to wrap yfinance, but yfinance is de facto toolkit for downloading stock quotes.  I would appreciate some guidance on fixing this.  If you think yfinance guys should deal with it, I can take it up with them as well.

**Comment by jealous** [comment]
Hi Satoshi,

I take a look at the problem.  Looks like I am not expecting this kind of input.  You need to do some transform to the data frame before you wrapped it.  Note the column cannot have multiple level of names like `('Open', 'VIXY')`.  You may need to somehow flatten the column levels.

It would take more effort to implement if we want to keep the same column format from yfinance.  I will mark it as help needed.

**Comment by satoshi** [comment]
Hi Cedric,

Thanks for taking an initial look.  Actually the multiple level names would be a great lead - I *think* they have a way to not do that.  Let me explore and get back to you.

**Comment by satoshi** [comment]
Cedric,

Looks like this flag is all we needed:
```
data = yf.download('VIXY', multi_level_index=False)

$ ./test.py 
[*********************100%***********************]  1 of 1 completed
                    close           high            low           open   volume
Date                                                                           
2011-01-04  633840.000000  650800.000000  633120.000000  633120.000000       14
```
Thank you very much for your help.  I've always used stockstats through pandas-datareader (which appears abandoned) and yfinance, but the yfinance peeps keep changing the API so an issue like this can occur.

I am not sure how other folks use stockstats, but if yfinance would be a common use case then you might want to document this usage.

**Comment by jealous** [comment]
Oh, glad to know there is a work around.  Thanks for sharing.
I partially fix the multi_level_index issue.  Will include in the next release.  The drawback is that I cannot add the extra index in the new columns.

**Comment by satoshi** [comment]
Cedric,

Thank you very much.  While I still needed to supply `multi_level_index=False`, 0.6.3 continues working and I'm glad we found a solution.

An excellent library by the way.  I love the ease of use when I only have to do `rsi_<d>` or `sma_<d>` to choose the periods I'm interested in.
