### ISSUE TITLE
Indicators limited by hardcoded periods

### ISSUE THREAD

**Issue by SamSlate** [jealous/stockstats#19]
MACD should not have hardcoded EMA periods- they need to be variable inputs.

Infact none of these functions should have hardcoded periods, it's *severely* limits the usefulness of an otherwise stellar wrapper.

**Comment by SamSlate** [comment]
Here's my (admittedly hamfisted attemt at a) custom MACD set of columns that adds some very useful functionality: 

`
def _get_macd_c(df, f=10, s=26, g=9):
    fast = df['close_'+str(f)+'_ema']
    slow = df['close_'+str(s)+'_ema']
    df['macd'] = fast - slow
    df['macds'] = df['macd_'+str(g)+'_ema']
    df['macdh'] = (df['macd'] - df['macds'])
    
    # macdh++
    df['macdh_pp'] = df.macdh.shift() < df.macdh
    # macdh > 0
    df['macdh_pos'] = df.macdh > 0
    # macdh approaching zero
    df['macdh_apr_z'] = (df.macdh_pp & ~df.macdh_pos) | (~df.macdh_pp & df.macdh_pos)
    # macd flipped
    df['macd_flipped'] = df.macdh_pos.shift() != df.macdh_pos

    del df['macdh_pp']
    del df['macdh_pos']
    del df['macd_'+str(g)+'_ema']
    del df['close_'+str(f)+'_ema']
    del df['close_'+str(s)+'_ema']
`

New to python, so I'm sure this doesn't follow best practices and can be improved -but it works and is very useful.

**Comment by jealous** [comment]
Good point.  I am extracting those default window parameters to class variables.
