### ISSUE TITLE
about cci

### ISSUE THREAD

**Issue by smallevil** [jealous/stockstats#20]
cci

cci sometimes 'inf'

![image](https://user-images.githubusercontent.com/198904/32336410-44f25d6e-bfbd-11e7-8f38-21dc708e3b1f.png)

**Comment by jealous** [comment]
Hi @smallevil , thanks for the info.
Could you supply your data so that I could debug the issue?

**Comment by jealous** [comment]
This could happen when the MAD is close to 0.  Please re-open this issue with more information.
