### ISSUE TITLE
How to install / setup up stockstats

### ISSUE THREAD

**Issue by toxilate** [jealous/stockstats#24]
Hey,

Wondering if somebody could help a guy out in getting this installed and setup up to use? I'm pretty new at this so any advice would be wonderful.

I have python installed, downloaded the files and I researched that I can get the "pandas.DataFrame" through Anaconda. Not sure where to go from here.

Thanks

**Comment by jealous** [comment]
@Sungod3000 you should call `stockstats.StockDataFrame.retype`

**Comment by Sungod3000** [comment]
thanks for the quick answer, i tried that before but ran into the next error. but good that i can exclude that from my troubleshooting list. 

you dont happen to have a clean example that shows the process from api calling a json object, choosing one column from json, converting to a pandas array and the converting to stockstats dataframe or something close to that?

**Comment by jealous** [comment]
No, I don't have that.  You need to have a `DataFrame` first.

**Comment by jealous** [comment]
Close this issue because there is no new feedback.
