### ISSUE TITLE
I get a warning

### ISSUE THREAD

**Issue by Denebulas** [jealous/stockstats#27]
When writing:
ss = Sdf.retype(dataf)
dataf['rsi_14'] = ss['rsi_14']

I get:

D:\PY\ANACONDA3\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy self._setitem_with_indexer(indexer, value)

Am I doing something wrong ?

**Comment by jealous** [comment]
fixed in 0.3.2
