### ISSUE TITLE
RSI 10 calculation

### ISSUE THREAD

**Issue by marcelopham** [jealous/stockstats#30]
Hello!
Question regarding how RSI 10 is calculated ... When providing a pandas dataframe

> df = pd.DataFrame(list)
recs = StockDataFrame.retype(df)
recs['rsi_10']

If I print out the dataframe:

> close                       970.27
id                           34156
volume        184.7046024000001694
close_-1_s                     NaN
close_-1_d                     NaN
rs_10                          NaN
rsi_10                         NaN
Name: 0, dtype: object
close                       970.49
id                           34157
volume        148.3538014100001874
close_-1_s                  970.27
close_-1_d                    0.22
rs_10                          inf
rsi_10                         100
Name: 1, dtype: object
close                       967.95
id                           34158
volume        108.4361391200002487
close_-1_s                  970.49
close_-1_d                   -2.54
rs_10                    0.0779528
rsi_10                     7.23156
Name: 2, dtype: object
close                       968.14
id                           34159
volume        125.0943135599999323
close_-1_s                  967.95
close_-1_d                    0.19
rs_10                     0.161067
rsi_10                     13.8724
...

The RSI 10 is already being calculated in the third row - isn't RSI 10 supposed to take the first 10 rows to calculate the initial RSI? 

Thanks! And sorry if this is not the place for questions, I searched on Stackoverflow and couldn't find any topic or keyword for stockstats

**Comment by jealous** [comment]
As far as I can tell, if the data is not sufficient, the underlying Pandas functions try their best to do the calculation.  I think you can ignore the data in the first 10 row.

**Comment by jealous** [comment]
The calculation of `RSI` uses `SMMA`.  In our implementation, we passed `min_periods=0` when calculating `SMMA`.  That means we take the data we have, even if they are not sufficient.
If you are not interested in these data, you can ignore them or reset them to `None`.
