### ISSUE TITLE
FutureWarning: Currently, 'apply' passes the values as ndarrays (raw=False)

### ISSUE THREAD

**Issue by kanendosei** [jealous/stockstats#37]
anaconda3/lib/python3.6/site-packages/stockstats.py:387: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  lambda x: np.fabs(x - x.mean()).mean())

Obviously, this is a quick fix. Has anyone else encountered it and is there a patch so we can `pip install -u stockstats` to resolve this issue?

**Comment by jealous** [comment]
I will try to include in next fix release.  Thanks for the info.

**Comment by jealous** [comment]
Not reproducible.  Close for now.  Please re-open it if you still see this.
