### ISSUE TITLE
Average True Range

### ISSUE THREAD

**Issue by romainecarter** [jealous/stockstats#4]
Do you have any plans to implement ATR?

**Comment by jealous** [comment]
Let me see what I can do.

**Comment by jealous** [comment]
I am checking the formula for ATR.
Wiki says it uses a SMMA of the TR(true range).
https://en.wikipedia.org/wiki/Average_true_range
But the stock trading client I am using is calculate it with a SMA of the TR.
I am following the formula in wiki for `atr`, you could retrieve the sma of tr with `tr_14_sma`.
The enhancement is included in 0.1.7.

**Comment by romainecarter** [comment]
Thanks.
