### ISSUE TITLE
Cant get EMA

### ISSUE THREAD

**Issue by MJeremy2017** [jealous/stockstats#41]
Hi, thanks for your contribution.
I was running the package and failed to get `EMA` with both 
> stock.get("ema")
and
> stock.get("EMA")

May I know how you get this?

**Comment by jealous** [comment]
`ema` requires parameters.  One is the column name, the other is the window size.  You could use `stock['close_5_ema']` to get an EMA on close price in a five day window.  Check the `test.py` for examples.

**Comment by MJeremy2017** [comment]
noted, thanks!
