### ISSUE TITLE
About ADX

### ISSUE THREAD

**Issue by liszhang** [jealous/stockstats#43]
Talking about the ADX index, I checked several programs and found the ADXs are all different. For stockstats, the ADX looks a bit higher than others. I am quite confused about this index calculation.

**Comment by jealous** [comment]
Hi @liszhang , this index has a window size.  Different window size results in different values.  The default window size used in stockstats is 6.  You can change the default value by changing `StockDataFrame.ADX_EMA`.  What's more, ADX is actually an exponential moving average of DX.  The way to calculate DX and the weight of the exponential moving average could all be different for different programs.
