### ISSUE TITLE
Question about _p option

### ISSUE THREAD

**Issue by 7ruth** [jealous/stockstats#44]
Could you please explain to me what something like this would do:
`close_-3,-1,+2_p`
`open_-1_d_-1,-3_p`

I looked at your tests, the main .py file and for the life of mine, can't figure out what __p_ does. 

Please advise.

**Comment by jealous** [comment]
Hi @7ruth ,

It calculates the binary representations of the specified date.  The purpose is to extract the specified data into a number.  It's hard to explain.  Let me use an example.

Say I have some data like this, the change column represents the change in the percentage of some data:
```
index    change
0        2.0
1        -1.3
2        3.0
3        1.8
```
In a case where I don't care about the detail number and only care about whether they are positive or negative.  You can convert all the positive numbers to 1 and negative numbers to 0.  it will be translated to:
```
index    change'
0        1
1        0
2        1
3        1
```
And now I want to know the permutation of `change'` column for the previous two days, it would be:

```
index    change'    change''
0        1          NA
1        0          NA
2        1          10  #the combination of index 0 and index 1
3        1          01  #the combination of index 1 and index 2
```
Now to make it easier to analysis, `_p` will convert the combination into a digital which results in 2 and 1.

It's only useful in some specific scenarios and is not a typical index.  Feel free to ignore this.

**Comment by 7ruth** [comment]
@jealous Thank you for this prompt and thorough explanation!
