### ISSUE TITLE
is TEMA and TRIX adjustable?

### ISSUE THREAD

**Issue by 7ruth** [jealous/stockstats#47]
are TEMA and TRIX adjustable like other metrics such as .get('tema_20') || .get('trix_35')

Couldn't find on stackoverflow or any other forums so I am at the source : D 

Awesome lib!

**Comment by jealous** [comment]
Thanks.  Yes, they have.  
For example, use `close_2_tema` to calculate the TEMA base on the close price for a window of 2.
`close_3_trix` calculate the trix based on the close price for a window of 3.

**Comment by 7ruth** [comment]
Thank you for such a quick response! 

Would you be open to a PR to the documentation/readme with that detail? 

I could add it under for example:
```
# TRIX, default to 12 days
stock['trix']
# MATRIX is the simple moving average of TRIX
stock['trix_9_sma']
# TEMA, another implementation for triple ema
stock['tema']
```

**Comment by jealous** [comment]
Sure.  Thanks for the suggestion.  I will try to include that in next commit.

**Comment by 7ruth** [comment]
Hello, I tried to push a branch with changes to make a PR with the change but not sure if you allow to do that. Thank you for the explanation, just added this to readme, sorry couldn't figure out how to make a PR to make your life easier:

```
    # TRIX, default to 12 days
    stock['trix']
    # TRIX based on the close price for a window of 3
    stock['close_3_trix']
    # MATRIX is the simple moving average of TRIX
    stock['trix_9_sma']
    # TEMA, another implementation for triple ema
    stock['tema']
    # TEMA based on the close price for a window of 2
    stock['close_2_tema']
```

**Comment by jealous** [comment]
Em, normally you can fork the repo to your own account.  You can always create new branches in your forked repo.  And then, you can create a PR from your own repo to this repo.  
This change is small, I will do that.  Thanks for trying to help. :)
