### ISSUE TITLE
Issue retrieving rsi_14

### ISSUE THREAD

**Issue by joshiparth1000** [jealous/stockstats#49]
I get the following error when I try to retrieve rsi_14. My dataframe looks like this:

              open      high       low     close    volume
date                                                      
20191113  261.1300  264.7800  261.0700  264.4200  20815595
20191112  261.5500  262.7900  260.9200  261.9600  21826100
20191111  258.3000  262.4700  258.2800  262.2000  20455300
20191108  258.6900  260.4400  256.8500  260.1400  17496600
20191107  258.7400  260.3500  258.1100  259.4300  23735100
...            ...       ...       ...       ...       ...
20190701  203.1700  204.4900  200.6500  201.5500  27253000
20190628  198.6800  199.4950  197.0500  197.9200  31110600
20190627  200.2900  201.5700  199.5700  199.7400  20899700
20190626  197.7700  200.9900  197.3494  199.8000  26067500
20190625  198.4300  199.2600  195.2900  195.5700  21070300

**Comment by jealous** [comment]
Hi Parth,

Could you attach the full data?  You could export it to a CSV.

**Comment by jealous** [comment]
Close due to no response.  Please re-open the issue with more information.
