### ISSUE TITLE
Request method to pull earnings per share

### ISSUE THREAD

**Issue by RednirgSkizzif** [jealous/stockstats#5]
I use this package. Ultimately I want to train neural nets with the data. Would really like to see an incorporation of the basic datas: P/E , EPS, P/B, PEG, etc. I can get this from yahoo finance (I think). But would like a one stop shop for all may data in a common format. Willing to help, but would need to be brought up to speed with the data frames.

**Comment by jealous** [comment]
Hi Dylan,

Thanks for the suggestion.  The stats I calculated in this package are all derived from basic information like `open`, `close`, `high`, `low`, `volume`.  The calculation of PE or EPS requires the historical data of financial data.  So far I am not sure how to retrieve them from yahoo finance.
And even if there is a way to retrieve them, I think these stats related to financial info should be long to another package.
Please let me know your thoughts.  Thanks.

**Comment by jealous** [comment]
Closed for now since it's been a long time and the stats is more like a financial info which cannot be calculated from basic historical trading data.
