### ISSUE TITLE
Could I set other values to StockDataFrame variables?

### ISSUE THREAD

**Issue by mscampos92** [jealous/stockstats#55]
I want to use other values for example in bollinger I would use 8 periods... how is the correct way to do it?

just do a "Sdf.BOLL_PERIOD = 8" ?

**Comment by jealous** [comment]
Yes.  That's right.

**Comment by danabaxia** [comment]
Hi this method seems not work for me. the option value changes but the boll results stay at 20 period

**Comment by jealous** [comment]
You need to set the value before you change the option.  The index are calculated when you access them for the first time.  You can also delete the old value so that the option will take effect when the lib calculates the new value.
