### ISSUE TITLE
ImportError: cannot import name 'StockDataFrame' from 'stockstats'

### ISSUE THREAD

**Issue by AllTheLonelyPeople** [jealous/stockstats#57]
I have stockstats installed with pip but I get the abovementioned error when i run:

`from stockstats import StockDataFrame as Sdf`

Any ideas?

**Comment by jealous** [comment]
Could you double-check your environment?  Looks like an environment issue to me.

**Comment by jealous** [comment]
Close for now.  Please re-open if you still have this issue.
