### ISSUE TITLE
MACDH doubled?

### ISSUE THREAD

**Issue by colinking** [jealous/stockstats#6]
Is there a reason why the MACD histogram value is [doubled](https://github.com/jealous/stockstats/blob/master/stockstats.py#L749)? From the resources I've seen and the trading client I use, it seems to be calculated as only the difference instead of double the difference.

(And thanks for your work on this library! It has saved me quite a bit of work on a side project of mine.)

**Comment by jealous** [comment]
Hi Colin, 

I compare the value with my own trading client.  In my trading client the value is doubled.  Just feel free to modify it or create a new alias for it in your own project.

**Comment by colinking** [comment]
Fair enough. Thanks!
