### ISSUE TITLE
Clearify prerequisites of DF column names

### ISSUE THREAD

**Issue by Pit-Storm** [jealous/stockstats#64]
Hi @jealous ,

thanks for your great package! This saves a lot of time 👍 

Unfortunately I have a few quick questions:

1. Can you specify what you mean by `amount`? (It is said int he Tutorial section of the Readme, where it is about to formalize the given data.) For me English is a foreign language and I'm not able to distinguish the semantics of volume and amount hardly.
2. Is it required to have all those columns in place for any kind of calculation or does one just have to provide the columns needed for calculating the value one is interested in? (Are there checks that alle columns have to be in place?)

Thank you for your work and kind regards 😊

**Comment by jealous** [comment]
Hi,

Volumn is the number of shares traded.  Mount is the money used to trade.  So normally:
mount = volumn * average price

No, you don't need alll of them.  Actually I don't think mount is used any where in the library.
I shall remove that in the doc.

Thanks
