### ISSUE TITLE
Traceback while using MACD_EMA_SHORT

### ISSUE THREAD

**Issue by Pit-Storm** [jealous/stockstats#65]
hi @jealous ,

I'm using your package for preparing data fro Algo trading in my masters thesis. During this I ran into some not understandable behaviour.

In the README file there are the usable indicators shown. When I want to use `MACD_EMA_SHORT` python gives me wall of text error message.

> tmp_df.get("macd_ema_short")
> macd_ema_short not found.
> Traceback (most recent call last):
>  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
>    return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
>  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
>  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
>  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'macd_ema_short'
>
> The above exception was the direct cause of the following exception:
>
>Traceback (most recent call last):
>  File "/usr/local/lib/python3.7/site-packages/stockstats.py", line 1021, in __getitem__
>    super(StockDataFrame, self).__getitem__(item))
>  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2902, in __getitem__
>    indexer = self.columns.get_loc(key)
>  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
>    raise KeyError(key) from err
> KeyError: 'macd_ema_short'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "/usr/local/lib/python3.7/site-packages/stockstats.py", line 1024, in __getitem__
>    self.init_columns(self, item)
>  File "/usr/local/lib/python3.7/site-packages/stockstats.py", line 955, in init_columns
>    StockDataFrame.__init_column(obj, columns)
>  File "/usr/local/lib/python3.7/site-packages/stockstats.py", line 1016, in __init_column
>    StockDataFrame.__init_not_exist_column(df, key)
>  File "/usr/local/lib/python3.7/site-packages/stockstats.py", line 1008, in __init_not_exist_column
>    getattr(cls, func_name)(df, r)
> AttributeError: type object 'StockDataFrame' has no attribute '_get_None'

I don't get the point here, because when I use `MACD` it generates three colums `macd`, `macds` and `macdh`.

Can you help me with `MACD_EMA_SHORT`? What am I missing?

Kind regards!

**Comment by jealous** [comment]
Hi,

I don't think we support `MACD_EMA_SHORT`.  By default, it only has `macd, `macds` and `macdh`.  It reports a not found error when the name you specified is not supported.
