### ISSUE TITLE
Groupby apply does not work with .get('macd')

### ISSUE THREAD

**Issue by Waffleboy** [jealous/stockstats#69]
I'm trying to get intraday macdh data, so did the following:

Example of df before doing anything:
![image](https://user-images.githubusercontent.com/12254813/108391907-21cc0880-724d-11eb-98cd-a35c66a54343.png)

```
def get_macdh(x):
    col = x.get('macdh')
    # do something with macdh
    result = True if col is not None else False
    return result

stock.groupby(['date','ticker']).apply(get_macdh)
```

Result:
```
date        ticker
2021-02-08  AAPL      False
            FB        False
2021-02-09  AAPL      False
            FB        False
2021-02-10  AAPL      False
            FB        False
2021-02-11  AAPL      False
            FB        False
2021-02-12  AAPL      False
            FB        False
2021-02-16  AAPL      False
            FB        False
2021-02-17  AAPL      False
            FB        False
```

It appears no matter what i try to do, `macdh` isnt getting initialized within the groupby? If i do a `stock.get('macdh')` before, the values will be wrong as itll include previous day figures as well.

**Comment by jealous** [comment]
Hi Thiru,

Could you check the type of the `groupBy` result?  We can only retrieve the statistics from a `StockDataFrame`.  Please make sure the type is correct.

**Comment by Waffleboy** [comment]
Hi @jealous 

`stock` is definitely a `StockDataFrame`, will running groupby on that result in a normal dataframe?

**Comment by jealous** [comment]
Yes, I think so.  `groupby` is a method supplied by the pandas `DataFrame`.  I guess the result is a pandas `DataFrame`.

**Comment by Waffleboy** [comment]
That fixed it, thanks! :)
