### ISSUE TITLE
Question about supported indicators

### ISSUE THREAD

**Issue by pablote** [jealous/stockstats#8]
does MACD support any other EMA besides (12,26,9)? maybe (5,35,5)?

also, is PPO supported? (http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:price_oscillators_ppo)

thanks, awesome lib!

**Comment by jealous** [comment]
Sorry, the answer for both questions are no.  I am marking them as enhancements.
* For the first one, the numbers are hard coded for now.  You could fork your own branch or just create your macd values by copying following code in `_get_macd`:
``` python
fast = df['close_5_ema']
slow = df['close_35_ema']
df['myMacd'] = fast - slow
df['myMacds'] = df['myMacd_5_ema']
df['myMacdh'] = 2 * (df['myMacd'] - df['myMacds'])
del df['myMacd_5_ema']
del fast
del slow
```
* I will work on PPO in the next release 😃

**Comment by jealous** [comment]
PPO added in the lastest master.
