### ISSUE TITLE
KDJ(20,5,5) How to set this parameter

### ISSUE THREAD

**Issue by guyqok** [jealous/stockstats#89]
How to set the three parameter of KDJ(20,5,5).

**Comment by jealous** [comment]
you can configure these parameters.
```
    KDJ_PARAM = (2.0 / 3.0, 1.0 / 3.0)
    KDJ_WINDOW = 9
```

**Comment by guyqok** [comment]
KDJ, default is (9,3,3) days. I want (20,5,5) so that I use stockStat['kdjk_20'].  But how to change it from the default 3 to 5. Which api should be used?

**Comment by jealous** [comment]
What do you mean by 3,3?  You can change the KDJ parameter directly with `StockDataFrame.KDJ_PARAM = ...`

**Comment by guyqok** [comment]
Configure the default paramters to the follow parameter for KDJ(20,5,5). It works. Thank you!  
    KDJ_PARAM = (4.0 / 5.0, 1.0 / 5.0)
    KDJ_WINDOW = 20
