### ISSUE TITLE
MACD histogram

### ISSUE THREAD

**Issue by pablote** [jealous/stockstats#9]
Why is the MACD histogram being multiplied by 2?:

```
df['macdh'] = 2 * (df['macd'] - df['macds'])
```

Every time I see it explained, it's defined as the difference between the MACD line and the signal line. 
Thanks

**Comment by jealous** [comment]
Hi @pablote , this is the algorithm used in the stock client that I am used to verify the calculation.  Maybe the 2 factor is used to amplify the difference.  Feel free to divide it by two if you prefer the version without the 2 factor.

**Comment by pablote** [comment]
ok, thanks
